//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadMate.DBConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Route = new HashSet<Route>();
            this.Route1 = new HashSet<Route>();
        }
    
        public int Address_id { get; set; }
        public int Street_id { get; set; }
        public string House_number { get; set; }
        public string Apartment_number { get; set; }
        public string Additional_info { get; set; }
    
        public virtual Street Street { get; set; }
        public virtual ICollection<Route> Route { get; set; }
        public virtual ICollection<Route> Route1 { get; set; }
    }
}
