//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadMate.DBConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo
    {
        public Cargo()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Cargo_id { get; set; }
        public int Client_id { get; set; }
        public int CargoType_id { get; set; }
        public string Description { get; set; }
        public decimal Weight_kg { get; set; }
        public decimal Volume_m3 { get; set; }
        public bool Is_fragile { get; set; }
        public bool Is_dangerous { get; set; }
        public string Special_requirements { get; set; }
        public System.DateTime Created_at { get; set; }
    
        public virtual CargoType CargoType { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
