//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadMate.DBConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.RouteIntermediatePoints = new HashSet<RouteIntermediatePoints>();
            this.Distance = new HashSet<Distance>();
            this.Distance1 = new HashSet<Distance>();
            this.Street = new HashSet<Street>();
        }
    
        public int City_id { get; set; }
        public int Region_id { get; set; }
        public string Name { get; set; }
        public string PostalCode { get; set; }
    
        public virtual ICollection<RouteIntermediatePoints> RouteIntermediatePoints { get; set; }
        public virtual Region Region { get; set; }
        public virtual ICollection<Distance> Distance { get; set; }
        public virtual ICollection<Distance> Distance1 { get; set; }
        public virtual ICollection<Street> Street { get; set; }
    }
}
