//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadMate.DBConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Region = new HashSet<Region>();
        }
    
        public int Country_id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<Region> Region { get; set; }
    }
}
