//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadMate.DBConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distance
    {
        public int Distance_id { get; set; }
        public int City_A_id { get; set; }
        public int City_B_id { get; set; }
        public decimal Distance_km { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
    }
}
