//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadMate.DBConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public Driver()
        {
            this.Truck = new HashSet<Truck>();
        }
    
        public int Driver_id { get; set; }
        public int User_id { get; set; }
        public int DriverStatus_id { get; set; }
        public string License_number { get; set; }
        public Nullable<System.DateTime> License_expiry_date { get; set; }
        public Nullable<int> Experience_years { get; set; }
        public System.DateTime Hire_date { get; set; }
    
        public virtual DriverStatus DriverStatus { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Truck> Truck { get; set; }
    }
}
