//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadMate.DBConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int Login_id { get; set; }
        public int User_id { get; set; }
        public string Username { get; set; }
        public string Password_hash { get; set; }
        public bool Is_active { get; set; }
        public int Failed_attempts { get; set; }
        public Nullable<System.DateTime> Last_login_attempt { get; set; }
        public Nullable<System.DateTime> Password_changed_at { get; set; }
    
        public virtual User User { get; set; }
    }
}
