//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadMate.DBConn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoadMateEntities : DbContext
    {
        public LoadMateEntities()
            : base("name=LoadMateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Address { get; set; }
        public DbSet<Cargo> Cargo { get; set; }
        public DbSet<CargoType> CargoType { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<Country> Country { get; set; }
        public DbSet<Driver> Driver { get; set; }
        public DbSet<DriverStatus> DriverStatus { get; set; }
        public DbSet<Gender> Gender { get; set; }
        public DbSet<Login> Login { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<OrderHistory> OrderHistory { get; set; }
        public DbSet<OrderStatus> OrderStatus { get; set; }
        public DbSet<Payment> Payment { get; set; }
        public DbSet<PaymentStatus> PaymentStatus { get; set; }
        public DbSet<Region> Region { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<Route> Route { get; set; }
        public DbSet<Street> Street { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tariff> Tariff { get; set; }
        public DbSet<Truck> Truck { get; set; }
        public DbSet<TruckStatus> TruckStatus { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<UserActivityLog> UserActivityLog { get; set; }
        public DbSet<UserStatus> UserStatus { get; set; }
    }
}
