//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadMate.DBConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderHistory = new HashSet<OrderHistory>();
            this.Payment = new HashSet<Payment>();
        }
    
        public int Order_id { get; set; }
        public Nullable<int> Manager_id { get; set; }
        public int Cargo_id { get; set; }
        public int Tariff_id { get; set; }
        public Nullable<int> Truck_id { get; set; }
        public int Route_id { get; set; }
        public int OrderStatus_id { get; set; }
        public string Order_number { get; set; }
        public System.DateTime Order_date { get; set; }
        public decimal Price { get; set; }
        public Nullable<System.DateTime> Scheduled_pickup { get; set; }
        public Nullable<System.DateTime> Scheduled_delivery { get; set; }
        public Nullable<System.DateTime> Actual_pickup { get; set; }
        public Nullable<System.DateTime> Actual_delivery { get; set; }
        public string Notes { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual User User { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Route Route { get; set; }
        public virtual Tariff Tariff { get; set; }
        public virtual Truck Truck { get; set; }
        public virtual ICollection<OrderHistory> OrderHistory { get; set; }
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
