//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadMate.DBConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHistory
    {
        public int History_id { get; set; }
        public int Order_id { get; set; }
        public int User_id { get; set; }
        public Nullable<int> Old_status_id { get; set; }
        public int New_status_id { get; set; }
        public string Comment { get; set; }
        public System.DateTime Changed_at { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual OrderStatus OrderStatus1 { get; set; }
        public virtual User User { get; set; }
    }
}
