//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadMate.DBConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Payment_id { get; set; }
        public int Order_id { get; set; }
        public int PaymentStatus_id { get; set; }
        public decimal Amount { get; set; }
        public string Payment_method { get; set; }
        public string Transaction_id { get; set; }
        public System.DateTime Transaction_date { get; set; }
        public Nullable<System.DateTime> Paid_date { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual PaymentStatus PaymentStatus { get; set; }
    }
}
