//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadMate.DBConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.City = new HashSet<City>();
        }
    
        public int Region_id { get; set; }
        public int Country_id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<City> City { get; set; }
        public virtual Country Country { get; set; }
    }
}
