//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadMate.DBConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public Route()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Route_id { get; set; }
        public int Start_address_id { get; set; }
        public int End_address_id { get; set; }
        public decimal Distance_km { get; set; }
        public decimal Estimated_time_hours { get; set; }
        public string Waypoints { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
