//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadMate.DBConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteIntermediatePoints
    {
        public int Point_id { get; set; }
        public int Route_id { get; set; }
        public int City_id { get; set; }
        public int Sequence_number { get; set; }
    
        public virtual City City { get; set; }
        public virtual Route Route { get; set; }
    }
}
