//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadMate.DBConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tariff
    {
        public Tariff()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Tariff_id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Cost_per_km { get; set; }
        public decimal Cost_per_kg { get; set; }
        public decimal Cost_per_m3 { get; set; }
        public decimal Additional_cost { get; set; }
        public Nullable<decimal> Min_price { get; set; }
        public bool Is_active { get; set; }
        public System.DateTime Created_time { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
    }
}
