//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadMate.DBConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truck
    {
        public Truck()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Truck_id { get; set; }
        public Nullable<int> Driver_id { get; set; }
        public int TruckStatus_id { get; set; }
        public string Model { get; set; }
        public string Registration_number { get; set; }
        public decimal Capacity_kg { get; set; }
        public decimal Capacity_m3 { get; set; }
        public string Dimensions { get; set; }
        public Nullable<int> Year_manufacture { get; set; }
        public Nullable<decimal> Fuel_consumption { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual TruckStatus TruckStatus { get; set; }
    }
}
