//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadMate.DBConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Cargo = new HashSet<Cargo>();
            this.Driver = new HashSet<Driver>();
            this.Login = new HashSet<Login>();
            this.Order = new HashSet<Order>();
            this.OrderHistory = new HashSet<OrderHistory>();
            this.UserActivityLog = new HashSet<UserActivityLog>();
        }
    
        public int User_id { get; set; }
        public int Role_id { get; set; }
        public Nullable<int> Gender_id { get; set; }
        public int UserStatus_id { get; set; }
        public string Full_name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime Created_at { get; set; }
        public Nullable<System.DateTime> Updated_at { get; set; }
        public Nullable<System.DateTime> Last_login { get; set; }
    
        public virtual ICollection<Cargo> Cargo { get; set; }
        public virtual ICollection<Driver> Driver { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ICollection<Login> Login { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<OrderHistory> OrderHistory { get; set; }
        public virtual Role Role { get; set; }
        public virtual UserStatus UserStatus { get; set; }
        public virtual ICollection<UserActivityLog> UserActivityLog { get; set; }
    }
}
