//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadMate.DBConn
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivityLog
    {
        public int Log_id { get; set; }
        public int User_id { get; set; }
        public string Action_type { get; set; }
        public string Description { get; set; }
        public string IP_address { get; set; }
        public System.DateTime Created_at { get; set; }
    
        public virtual User User { get; set; }
    }
}
